name: CI/CD Pipeline

on:
  push:
    branches:
      - backend # backend 브랜치에 푸시될 때 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # 최신 버전으로 업데이트
        with:
          path: back # back 폴더만 클론

      - name: Set up Node.js
        uses: actions/setup-node@v3 # 최신 버전으로 업데이트
        with:
          node-version: "20" # Node.js 20으로 업데이트

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: cd back && pnpm install # back 폴더로 이동하여 의존성 설치

      - name: Build project
        run: cd back && pnpm run build # back 폴더로 이동하여 프로젝트 빌드

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: cd back && docker build -t hotchapa/burger-nest:latest . # back 폴더에서 Docker 이미지를 빌드

      - name: Push Docker image to Docker Hub
        run: docker push hotchapa/burger-nest:latest # Docker 이미지를 Docker Hub에 푸시

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # 최신 버전으로 업데이트
        with:
          path: back # back 폴더만 클론

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} ubuntu@your-ec2-ip << 'EOF'
            docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
            docker pull hotchapa/burger-nest:latest 
            docker-compose -f /path/to/your/docker-compose.yml up -d 
          EOF
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }} # Docker Hub 사용자 이름
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }} # Docker Hub 비밀번호
          EC2_KEY: ${{ secrets.EC2_KEY }} # EC2 인스턴스에 접근하기 위한 SSH 키
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }} # MySQL 루트 비밀번호
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }} # MySQL 데이터베이스 이름
          MYSQL_USER: ${{ secrets.MYSQL_USER }} # MySQL 사용자 이름
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }} # MySQL 사용자 비밀번호
